server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal: internal_exchange
  queues:
    notification: notification_queue
  routing-keys:
    internal-notification: internal_notification_routing_key
