server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sxlecquer/microservices # this repository is public, so there is no need to specify username and password

management:
  tracing:
    sampling:
      probability: 1.0